### ISSUE TITLE
Ideas for v3.2.0

### ISSUE THREAD

**Issue by JamenMarz** [iora/iora#6]
# To-do high-priority 
- [x] <s>Make `iora.json` act as index.</s>: Determined not useful. 
- [ ] Method in routes. `GET /foo/bar`
- [ ] `iora init`
- [ ] `iora bg`
- [ ] `iora stop`
- [ ] `iora install`
- [x] `"disabled": true` -> `"enabled": false`
- [x] Better `.listen` errors.

# To-do low-priority
 - [ ] Global configuration
 - [ ] _iora hooks_
 - [ ] `iora config`
 - [ ] `iora monitor`

**Comment by JamenMarz** [comment]
Another idea, global configuration and _iora hooks_.

 - Global configuration would be to more-so set defaults for all your iora servers, that way you could omit certain fields if they're going to consistently be the same across many servers.
 - _iora hooks_ would be packages that hook directly into iora.  This way middleware can implement custom commands into iora.

**Comment by ConnorHartley** [comment]
Only one idea currently:

- Change ` "https": {
    "disabled": true
  } ` to ` "https": {
    "enabled": false
  } ` to give a better understanding.

**Comment by JamenMarz** [comment]
Some ideas relating to errors, It'd be helpful if I made the `EACESS` error for running look more nice.  It basically means that you don't have privileges to run on a port that low (such as 80 or 443).  Currently prints something along the lines of:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
```

Which can be confusing.

**Comment by JamenMarz** [comment]
I think that's a good place for v3.2.  I'll start on it. :)

**Comment by JamenMarz** [comment]
- [ ] `iora.json` act as index.
- [ ] Method in routes.
- [ ] `iora init`
- [ ] `iora bg`
- [ ] `iora stop`
- [ ] `iora install`
- [ ] `"disabled": true` -> `"enabled": false`
- [ ] Better `.listen` errors.

**Comment by JamenMarz** [comment]
I've repoened the issue and turned it into a list.  I'll close it with a v3.2 commit.

**Comment by JamenMarz** [comment]
These ideas will actually be implemented right into v4.  We're skipping over v3.2 and heading straight towards a redesign.
